// app/layout.tsx
import { Providers } from "./providers";
import './globals.css'
import { Inter } from 'next/font/google'
import { useRouter } from "next/navigation";
import { useEffect } from "react";
// import { userService } from '../services/userService';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();

  // useEffect(() => {
  //     if (userService.userValue) {
  //         router.push('/');
  //     }
  // }, []);

  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}